<a href="https://colab.research.google.com/github/kkeshavsharma/NLP_Practice/blob/main/NLP_Prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_parquet("comments_data_13.parquet")

In [ ]:
df.columns

Index(['video_id', 'channel_id', 'comment_id', 'author_display_name',
       'author_channel_id', 'text_display', 'like_count', 'published_at',
       'updated_at'],
      dtype='object')

In [ ]:
df['text_display'] = df['text_display'].str.replace(r'<[^<>]*>', '', regex=True)
df = df.drop_duplicates(subset = ["text_display"])
df= df.groupby('video_id')['text_display'].apply(lambda x: ' '.join(x)).reset_index()

In [ ]:
import pandas as pd
import re

def advanced_nlp_clean(series: pd.Series) -> pd.Series:
    series = series.fillna("").astype(str)

    # 1. Remove URLs and HTML (Your existing fast regex)
    series = series.str.replace(r'https?://\S+|www\.\S+', '', regex=True)
    series = series.str.replace(r'<[^<>]*>', '', regex=True)

    # 2. Normalize possessives (Officer's -> Officer)
    series = series.str.replace(r"['’][sS]\b", '', regex=True)

    # 3. Remove YouTube specific noise (e.g., timestamps like 12:34)
    # Timestamps are common in comments but don't help classify the video type
    series = series.str.replace(r'\b\d{1,2}:\d{2}(:\d{2})?\b', '', regex=True)

    # 4. Handle excessive character repetition (e.g., "goooood" -> "good")
    # This prevents the model from treating "coool" and "cool" as completely unique words
    series = series.str.replace(r'(.)\1{2,}', r'\1\1', regex=True)

    # 5. Clean up extra whitespaces
    series = series.str.replace(r'\s+', ' ', regex=True).str.strip()

    return series

text_df = advanced_nlp_clean(df["text_display"])

In [ ]:
text_df

0       CAIIB MAHAPACK 2.0 🔥👉 ENROLL NOW - FOR DISCOUN...
1       same here❤ Cleared in first attemptThankyou ad...
2       Thank you mam, I cleared exam. Nice class mam ...
3       please take more sessions. you teach practical...
4                                Thank you very much, Sir
                              ...
3191    JAIIB &amp; CAIIB MAHAPACKS 2.0 - Use Coupon:-...
3192                             kis date ki video h ye ?
3193    Thanks a lot ma&#39;am for this wonderful sess...
3194    Yes audio, video are ok but at the end of the ...
3195    ✅ Officer&#39;s batch (Bilingual)📌 Join Now Co...
Name: text_display, Length: 3196, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the vectorizer
# max_features=10000 means keep only the top 10k most important words across your dataset
# ngram_range=(1,2) means look at single words ("python") AND two-word phrases ("machine learning")
tfidf = TfidfVectorizer(max_features=10000, ngram_range=(1, 2))

comments = tfidf.fit_transform(comments_per_video['text_display'])

In [ ]:
pd.DataFrame(comments)

                                                      0
0     <Compressed Sparse Row sparse matrix of dtype ...
1     <Compressed Sparse Row sparse matrix of dtype ...
2     <Compressed Sparse Row sparse matrix of dtype ...
3     <Compressed Sparse Row sparse matrix of dtype ...
4     <Compressed Sparse Row sparse matrix of dtype ...
...                                                 ...
3189  <Compressed Sparse Row sparse matrix of dtype ...
3190  <Compressed Sparse Row sparse matrix of dtype ...
3191  <Compressed Sparse Row sparse matrix of dtype ...
3192  <Compressed Sparse Row sparse matrix of dtype ...
3193  <Compressed Sparse Row sparse matrix of dtype ...

[3194 rows x 1 columns]

In [ ]:
!pip install transformers datasets torch

Requirement already satisfied: transformers in /usr/local/lib/python3.13/dist-packages (5.18.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.13/dist-packages (4.8.5)
Requirement already satisfied: torch in /usr/local/lib/python3.13/dist-packages (2.11.0+cpu)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (1.33.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.23.2)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.13/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.7)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.12.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch) (3.1.6)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (1.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2026.4)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.25.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
ERROR: Operation cancelled by user

In [ ]:
import torch
from transformers import BertTokenizer, BertModel

# Load pre-trained BERT tokenizer and model (uncased version)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
text = text_df.apply(str).tolist()
inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True)

# Check token IDs and attention mask
print("Input IDs:", inputs['input_ids'])
print("Attention Mask:", inputs['attention_mask'])

Input IDs: tensor([[  101, 29080, 12322,  ...,     0,     0,     0],
        [  101,  2168,   100,  ...,     0,     0,     0],
        [  101,  4067,  2017,  ...,     0,     0,     0],
        ...,
        [  101,  4283,  1037,  ...,     0,     0,     0],
        [  101,  2748,  5746,  ...,     0,     0,     0],
        [  101,   100,  2961,  ...,     0,     0,     0]])
Attention Mask: tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])

In [ ]:
pd.DataFrame(inputs["input_ids"])

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
0,101,29080,12322,24404,23947,1016,1012,1014,100,25612,...,0,0,0,0,0,0,0,0,0,0
1,101,2168,100,5985,1999,2034,3535,21604,4801,7140,...,0,0,0,0,0,0,0,0,0,0
2,101,4067,2017,5003,2213,1010,1045,5985,11360,1012,...,0,0,0,0,0,0,0,0,0,0
3,101,3531,2202,2062,6521,1012,2017,6570,8134,1998,...,0,0,0,0,0,0,0,0,0,0
4,101,4067,2017,2200,2172,1010,2909,102,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3191,101,17410,12322,1004,23713,1025,29080,12322,24404,23947,...,0,0,0,0,0,0,0,0,0,0
3192,101,11382,2015,3058,11382,2678,1044,6300,1029,102,...,0,0,0,0,0,0,0,0,0,0
3193,101,4283,1037,2843,5003,1004,1001,4464,1025,2572,...,0,0,0,0,0,0,0,0,0,0
3194,101,2748,5746,1010,2678,2024,7929,2021,2012,1996,...,0,0,0,0,0,0,0,0,0,0
3195,101,100,2961,1004,1001,4464,1025,1055,14108,1006,...,0,0,0,0,0,0,0,0,0,0